# Version에 따라서 compose 문법이 다름
version: '3'

volumes: # 컨테이너 별로 volume이 있지만 이는 컨테이너가 꺼지면 사라지기 때문에 도커 볼륨이 필요
  mariadb-volume:
    name: mariadb-volume
    driver: local # host의 파일 시스템 사용
    driver_opts: 
      type: none # 단순히 host dir를 바인드 마운트
      device: /home/sangylee/data/mariadb # host의 dir path
      o: bind # host 시스템의 dir이나 file을 컨테이너에 연결하는 방식 -> bind mount 방식
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/sangylee/data/wordpress
      o: bind

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    build: ./requirements/mariadb
    networks:
      - inception
    expose:
      - "3306"
    tty: true
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress-volume:/var/www/html
    build: ./requirements/wordpress
    networks:
      - inception
    expose:
      - '9000'
    tty: true
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress-volume:/var/www/html
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - '443:443'
    tty: true
    restart: always
      

networks:
  inception: # network name
    driver: bridge # default = bridge